### ISSUE TITLE
WebCodec Support

### ISSUE THREAD

**Issue by atiernan** [fpvout/fpv-browser#2]
### What:
Start using WebCodecs to decode and display the H.264 video stream

### Why:
JMuxer is currently used to decode and render the video stream, however it is a purely javascript solution that adds considerable latency. WebCodecs use the codecs used by the browser to decode the video and therefore offer a solution that adds far less latecy.

### Requirements:
- The initial solution should default to JMuxer. If WebCodecs are available, the user should be able to enable them
- As WebCodecs are currently in an origin trial, the following meta tag should be added to the html template
    `<meta http-equiv="origin-trial" content="Ai6skJj2lyH5e2FNv8q3AJrvApFLk0nxv8as7CXZcfNYTbpvSkq+NRXHPuVpd9lJ2sKHYIVD6OXTw9gy7HaXsQ8AAABSeyJvcmlnaW4iOiJodHRwczovL2xpdmUuZnB2b3V0LmNvbTo0NDMiLCJmZWF0dXJlIjoiV2ViQ29kZWNzIiwiZXhwaXJ5IjoxNjI2MjIwNzk5fQ==">`

**Comment by sahibalejandro** [comment]
@atiernan Is this branch still a WIP? Is there anything I can help with to close this issue?
I can continue where you left, just let me know.

**Comment by atiernan** [comment]
It's still WIP but I can't remember the state I left it in. I think it was working fairly well, so feel free to pick up where I left it, at the very least the following needs doing:
1. WebCodecs are now shipping in chrome, so the origin trial meta tag can be removed.
2. The code needs a general clean up
