### ISSUE TITLE
Connect to googles not working 

### ISSUE THREAD

**Issue by SebastianKumor** [fpvout/fpv-browser#9]
Hey guys, I cloned your repo last week while it was just a connect button and a label and the website worked fine on my mac and google chrome. I just pulled the latest changes and the connect button no longer gives me the prompt from chrome to choose a device. When I plug the googles and click the connect button nothing happens.

I checkout out few commits back and it started working again. I came to conclusion that commit `d96c2c0e904ad27e28f5727d7635f16b1b94836b` is when it stops working for me and I cannot get connection to my googles. I am using v2 googles

**Comment by atiernan** [comment]
Do you get any errors in the chrome devtools?

**Comment by SebastianKumor** [comment]
@atiernan hey sorry for a late reply but here is some console logs and some errors. I do not get these on the earlier versions.
 
<img width="521" alt="Screenshot 2021-06-22 at 09 35 35" src="https://user-images.githubusercontent.com/8973431/122883447-7f787a80-d33d-11eb-840a-949062349a7a.png">
<img width="556" alt="Screenshot 2021-06-22 at 09 34 41" src="https://user-images.githubusercontent.com/8973431/122883453-80a9a780-d33d-11eb-8940-83c2cb65d835.png">

**Comment by atiernan** [comment]
What OS and version of Chrome are you using?

**Comment by SebastianKumor** [comment]
@atiernan macOS 11.4 and chrome 91.0.4472.114

**Comment by shulhi** [comment]
I'm also not able to connect but with access denied error in the console.

**Comment by florian-senn** [comment]
@shulhi  @SebastianKumor Did you already try Zadig and different USB drivers?

**Comment by shulhi** [comment]
> @shulhi  @SebastianKumor Did you already try Zadig and different USB drivers?
> 

I'm using Ubuntu.I'll give it another go because it might be permission issue, the goggle was detected.

**Comment by SebastianKumor** [comment]
@florian-senn seems like this zadig is only for windows? Not sure how that will help me. Also the older version of this app worked for me so I assume someone changed something while updating the UI

**Comment by florian-senn** [comment]
@shulhi @SebastianKumor yeah, guess it's only for Windows, so it's not the right solution for your problem unfortunately...

**Comment by sahibalejandro** [comment]
@SebastianKumor @atiernan This could be due to the fact that `https` flag was removed from the `devServer` config, here:
https://github.com/fpvout/live.fpvout.com/commit/d96c2c0e904ad27e28f5727d7635f16b1b94836b#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fL18

I just added it and `navigator.usb` is no longer `undefined`, USB devices prompt appears again.

~I can make the PR to add the flag again if you guys agree.~ I just did a PR.
